services:
  postgres:
    image: postgres:16
    container_name: pulseops-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: rainz
      POSTGRES_PASSWORD: brainz
      POSTGRES_DB: pulseops
    ports:
      - "5432:5432"
    volumes:
      - pulseops_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: pulseops_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pulseops_postgres_data:
